[build]
  command = "chmod +x scripts/build-netlify.sh && ./scripts/build-netlify.sh"
  publish = "."

# Configure secrets scanning to allow expected files
[build.environment]
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_PATHS = ".env,config/**,assets/js/env.*.js,scripts/**,docs/**,.github/**,*.md"
  SECRETS_SCAN_OMIT_KEYS = "APP_NAME,NODE_ENV,APP_VERSION,TMDB_API_KEY"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    files = ["assets/js/netlify-env.js"]

# Redirect rules for clean URLs
[[redirects]]
  from = "/person/*"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/movie/*"
  to = "/movie.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
