#!/bin/bash
# Netlify build script for MyFilmPeople
# Creates environment file with API key for production

set -e

echo "Building MyFilmPeople for Netlify..."

# TMDB API key (safe for client-side apps)
API_KEY="5f1ead96e48e2379102c77c2546331a4"

echo "Creating production environment file..."

# Create the Netlify environment JavaScript file
cat > assets/js/env.netlify.js << EOF
// Auto-generated by Netlify build process
// TMDB API key for client-side usage

window.NETLIFY_ENV_TMDB_API_KEY = '$API_KEY';
console.log('✅ Netlify API key loaded successfully');
EOF

echo "Updating HTML files to include Netlify environment..."

# Function to update HTML files
update_html_file() {
    local file=$1
    echo "Updating $file..."
    
    # Check if env.netlify.js is already included
    if ! grep -q "env.netlify.js" "$file"; then
        # Add env.netlify.js before config.local.js
        sed -i 's|<script src="assets/js/config.local.js"|<script src="assets/js/env.netlify.js"></script>\n    <script src="assets/js/config.local.js"|g' "$file"
        echo "✅ Added env.netlify.js to $file"
    else
        echo "✅ env.netlify.js already included in $file"
    fi
}

# Update all HTML files
update_html_file "index.html"
update_html_file "movie.html"
update_html_file "profile.html"

echo "✅ Build complete!"
echo "📱 Site ready for deployment with API key configured"
